// Generated by https://quicktype.io

import { TransList } from "./TransList";

export interface UserDetail {
    email:     string;
    fullname:  string;
    joinedOn:  string;
    transList: TransList[];
}
